name: Workflow without Delay

on:
  push:
    branches:
      - master

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
    - name: Print Command
      env:
        TOKEN: ${{secrets.GITHUB_TOKEN}}
        JENKINS_CREDENTIALS: ${{secrets.JENKINS_CREDENTIALS}}
        JENKINS_BUILD_TRIGGER_URL: https://rentmeester-webhook.wolt.com/job/rentmeester-deploy/buildWithParameters?project=payment-service&environment=master&version=${{github.sha}}
      run: |
        DEPLOYMENT_URL=$(curl --silent \
          --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/deployments \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "ref": "${{github.sha}}",
            "environment": "test-workflow",
            "required_contexts": []
          }' | jq -r ".url")

        echo "Token: ${TOKEN:0:4} ${TOKEN:4}"
        echo "Command: ./update_status.sh \"in_progress\" \"${TOKEN:0:4}\" \"${TOKEN:4}\" \"$DEPLOYMENT_URL/statuses\""
